[package]
name        = "sns-polylux-theme"
version     = "0.1.0"
entrypoint  = "sns-theme.typ"
authors     = ["M. Barbieri <https://mbarbieri.it>"]
license     = "MIT-0"
description = "Unofficial template for slides in Polylux"
repository  = "GitLab <https://gitlab.com/martino.barbieri/polylux-sns-template>"
keywords    = ["polylux","template","slide","slides","SNS","UniPi","presentation","talk","lecture","lectures"]
categories  = ["presentation"]
compiler    = "0.12.0"
exclude     = ["env.sh","*/.pdf"]

[template]
path        = "template"
entrypoint  = "main.typ"
thumbnail   = "thumbnail.png"
